# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46b0667150c499b235a17ce8723e868da113e832478547b8dc7e7bdcaf4afd1c77d45679fd818ebebdddc3f9cb4d13b9e5230591a7768392199c3a915b687e67

test:
  secret_key_base: 19597094bd313e3754e71a9a80d866812e5fb1d683eb28efc3ed986daa7effdb505532579833d20d43fecf7a14e2d4328975bb702e2539bea5e728d37af016f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
